print("HR Decisions")

tReligionEvents_1.RELIGION_BIRD_FIGURE = {[3] = "BIRD_FIGURE"}
tReligionEvents_1.RELIGION_AKATTU = {[3] = "AKATTU"}
tReligionEvents_1.RELIGION_SAMAN = {[3] = "SAMAN"}
tReligionEvents_1.RELIGION_INTIISM = {[3] = "INTIISM"}
tReligionEvents_1.RELIGION_PUTA_TUPUNA = {[3] = "PUTA_TUPUNA"}
tReligionEvents_1.RELIGION_TANGATA_MANU = {[3] = "TANGATA_MANU"}
tReligionEvents_1.RELIGION_ASHURISM = {[3] = "ASHURISM"}
tReligionEvents_1.RELIGION_SISKURMES = {[3] = "SISKURMES"}
tReligionEvents_1.RELIGION_MAHOMA = {[3] = "MAHOMA"}
tReligionEvents_1.RELIGION_MIDEWIWIN = {[3] = "MIDEWIWIN"}
tReligionEvents_1.RELIGION_SAIRIMAISM = {[3] = "SAIRIMAISM"}
tReligionEvents_1.RELIGION_SOUTHERN_CULT = {[3] = "SOUTHERN_CULT"}
tReligionEvents_1.RELIGION_MUTAZILA = {[3] = "MUTAZILA"}
tReligionEvents_1.RELIGION_SHIVA = {[3] = "SHIVA"}
tReligionEvents_1.RELIGION_VEDIC = {[3] = "VEDIC"}
tReligionEvents_1.RELIGION_DRUZE = {[3] = "DRUZE"}
tReligionEvents_1.RELIGION_AHMADI = {[3] = "AHMADI"}
tReligionEvents_1.RELIGION_NEOPLATONISM = {[3] = "NEOPLATONISM"}
tReligionEvents_1.RELIGION_HERMETICISM = {[3] = "HERMETICISM"}
tReligionEvents_1.RELIGION_JAIN = {[3] = "JAIN"}
tReligionEvents_1.RELIGION_NUM = {[3] = "NUM"}
tReligionEvents_1.RELIGION_SATSANA_PHI = {[3] = "SATSANA_PHI"}
tReligionEvents_1.RELIGION_MUISM = {[3] = "MUISM"}
tReligionEvents_1.RELIGION_VODUN = {[3] = "VODUN"}
tReligionEvents_1.RELIGION_AMANAIISM = {[3] = "AMANAIISM"}
tReligionEvents_1.RELIGION_ATENISM = {[3] = "ATENISM"}
tReligionEvents_1.RELIGION_CHRISTIAN_ANGLICANISM = {[3] = "ANGLICANISM"}
tReligionEvents_1.RELIGION_BAHAI = {[3] = "BAHAI"}
tReligionEvents_1.RELIGION_MANICHAEISM = {[3] = "MANICHAEISM"}
tReligionEvents_1.RELIGION_MITHRAISM = {[3] = "MITHRAISM"}
tReligionEvents_1.RELIGION_CHRISTIAN_MORMONISM = {[3] = "MORMONISM"}
tReligionEvents_1.RELIGION_TZOLKIN = {[3] = "TZOLKIN"}
tReligionEvents_1.RELIGION_SANTERIA = {[3] = "SANTERIA"}
tReligionEvents_1.RELIGION_CHRISTIAN_ARIANISM = {[3] = "ARIANISM"}
tReligionEvents_1.RELIGION_ATANODJUWAJA = {[3] = "ATANODJUWAJA"}
tReligionEvents_1.RELIGION_BOGOMILISM = {[3] = "BOGOMILISM"}
tReligionEvents_1.RELIGION_CATHARISM = {[3] = "CATHARISM"}
tReligionEvents_1.RELIGION_HUSSITISM = {[3] = "HUSSITISM"}
tReligionEvents_1.RELIGION_SLAVIANISM = {[3] = "SLAVIANISM"}
tReligionEvents_1.RELIGION_ROMUVA = {[3] = "ROMUVA"}
tReligionEvents_1.RELIGION_AL_ASNAM = {[3] = "ASNAM"}
tReligionEvents_1.RELIGION_NAPIRTUNIIS = {[3] = "NAPIRTUNIIS"}
tReligionEvents_1.RELIGION_MANDEANISM = {[3] = "MANDEANISM"}
tReligionEvents_1.RELIGION_ANGAKKUQISM = {[3] = "ANGAKKUQISM"}
tReligionEvents_1.RELIGION_CHIMINAGUA = {[3] = "CHIMINAGUA"}
tReligionEvents_1.RELIGION_NUMENISM = {[3] = "NUMENISM"}
tReligionEvents_1.RELIGION_IMPERIAL_CULT = {[3] = "IMPERIAL_CULT"}
tReligionEvents_1.RELIGION_HEROS_KARABAZMOS = {[3] = "HEROS_KARABAZMOS"}
tReligionEvents_1.RELIGION_ZEMIISM = {[3] = "ZEMIISM"}
tReligionEvents_1.RELIGION_YAZDANISM = {[3] = "YAZDANISM"}
tReligionEvents_1.RELIGION_TJUKURPA = {[3] = "TJUKURPA"}
tReligionEvents_1.RELIGION_ODINANI = {[3] = "ODINANI"}
tReligionEvents_1.RELIGION_KACHINA = {[3] = "KACHINA"}
tReligionEvents_1.RELIGION_LAIBONI = {[3] = "LAIBONI"}
tReligionEvents_1.RELIGION_ONYAMESOM = {[3] = "ONYAMESOM"}
tReligionEvents_1.RELIGION_FAT_ROOG = {[3] = "FAT_ROOG"}
tReligionEvents_1.RELIGION_RAZANA = {[3] = "RAZANA"}
tReligionEvents_1.RELIGION_BUMUNTU = {[3] = "BUMUNTU"}
tReligionEvents_1.RELIGION_PAJELANCA = {[3] = "PAJELANCA"}
tReligionEvents_1.RELIGION_SGAANAANG = {[3] = "SGAANAANG"}
tReligionEvents_1.RELIGION_PROTESTANT_BAPTIST = {[3] = "BAPTIST"}
tReligionEvents_1.RELIGION_MYSTERIES = {[3] = "MYSTERIES"}
tReligionEvents_1.RELIGION_TEMAUKELISM = {[3] = "TEMAUKELISM"}
tReligionEvents_1.RELIGION_MWARI = {[3] = "MWARI"}
tReligionEvents_1.RELIGION_ANITO = {[3] = "ANITO"}
tReligionEvents_1.RELIGION_MALAGAN = {[3] = "MALAGAN"}
tReligionEvents_1.RELIGION_ITANG = {[3] = "ITANG"}