UPDATE Buildings
SET FreeBuildingThisCity = 'BUILDINGCLASS_EE_MENAGERIE'
WHERE Type = 'BUILDING_FW_JURASSIC_PARK'
AND EXISTS (SELECT * FROM Units WHERE TYPE = 'UNIT_EE_SKIRMISHER');

UPDATE Building_BuildingClassYieldChanges
SET BuildingClassType = 'BUILDINGCLASS_EE_MENAGERIE'
WHERE BuildingType = 'BUILDING_FW_JURASSIC_PARK'
AND EXISTS (SELECT * FROM Units WHERE TYPE = 'UNIT_EE_SKIRMISHER');

UPDATE Building_BuildingClassHappiness
SET BuildingClassType = 'BUILDINGCLASS_EE_MENAGERIE'
WHERE BuildingType = 'BUILDING_FW_JURASSIC_PARK'
AND EXISTS (SELECT * FROM Units WHERE TYPE = 'UNIT_EE_SKIRMISHER');